CC=gcc
CFLAGS=-Wall -pthread

EXE= \
	pthread_game \
	pthread_hello_world \
	pthread_sharing \
	pthread_exit \
	pthread_mutex \
	pthread_producer_consumer \
	normal_strtok \
	pthread_strtok \
	pthread_strtok_r \

all: ${EXE}

clean:
	rm -f ${EXE}
