CC=gcc
CFLAGS=-Wall -O0

EXE=\
	time_example \
	printf_example_slow \
	printf_example_fast \
	zombie\
	share_opened_file \
        segv \
	reparent \
	process_group \


all: ${EXE}

clean:
	rm -f ${EXE} data.txt
