CC=gcc
CFLAGS=-Wall -O0

EXE=\
	mmap_read \
	mmap_write \
	mmap_vs \
	read_vs \
	branch_prediction \
	branch_prediction_opt \
	branch_prediction_opt_why \
	loop_unrolling_before \
	loop_unrolling_after \

all: ${EXE}

clean:
	rm -f ${EXE} *~
