CC=gcc
CFLAGS=-Wall -O0

EXE=\
	time_example \
	printf_example_slow \
	printf_example_fast \
	zombie\
	share_opened_file \
	suicide \
        handle_int \
        break_sleep \
        many_signal \
        segv \
        pause \
        infinite_loop \
        alarm \
        alarm_fgets \
	reparent \


all: ${EXE}

clean:
	rm -f ${EXE} data.txt
